### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by GrahamCampbell** [notifymehq/notifyme#37]
* [x] Move gateways to their own namespace (done in #30)
* [x] Cleanup the abstract gateway and contracts (done in #30)
* [x] Remove dependence on laravel (done in #38)
* [x] Create laravel 4 and laravel 5 bridges (done in [laravel4](https://github.com/notifymehq/laravel4) and [laravel5](https://github.com/notifymehq/laravel5))
* [x] Move each gateway to their own repo (in progress in #39)

---
Replaces #7 and #15. // cc @jbrooksuk, @joecohens, @frankdejonge

**Comment by GrahamCampbell** [comment]
Question - do we need a larave4 bridge and a laravel5 bridge, or should we just move forward with L5?

**Comment by jbrooksuk** [comment]
Both for now. We can deprecate in the future.

**Comment by GrahamCampbell** [comment]
Should we name them laravel4-notifyme and laravel5-notifyme?

**Comment by GrahamCampbell** [comment]
notifyme-laravel4?

**Comment by GrahamCampbell** [comment]
or just "laravel4"

**Comment by GrahamCampbell** [comment]
Going for just laravel4 and laravel5.

**Comment by joecohens** [comment]
Yeah both for now
